?# -*- coding: utf-8 -*-
"""21AIA62-FDSA Assignment

Automatically generated by Colaboratory.

Original file is located at

https://colab.research.google.com/drive/1WOM C6qj8p6kJDv3 fnWECPRLWC8mXRTOa

#*EQUAL* SAMPLE SIZE

import numpy as np 
from scipy import stats
from sklearn.model_selection import
train_test_split

from sklearn import datasets 
iris=datasets.load_iris() 
sep_length = iris.data[:0] 
sep_width=iris.data[:0]

a_1, a_2 train_test_split(sep_length, test_size=0.4, random_state=0) 
b_1, b_2 = train_test_split (sep_length, test_size=0.4, random_state=1)

mu1 = np.mean(a_1)

mu2 = np.mean(b_1)

print("Standard Deviation of sample A", np.std (a_1))

print("Standard Deviation of sample B", np.std (b_1))
val-stats.ttest_ind (a_1, b_1, equal_var = False)
val

if (val.pvalue>0.05):
print("Reject Null Hypothesis")
else:
print("Accept Null Hypothesis")

"""#unequal sample size"""

a_1, a_2 = train_test_split(sep_length, test_size=0.4, random_state=0)
b_1, b_2 = train_test_split(sep_length, test_size=0.5, random_state=1)

mu1 = np.mean (a_1)

mu2 = np.mean (b_1)

print("Standard Deviation of sample A", np.std (a_1))

print("Standard Deviation of sample B", np. std (b_1))

val=stats.ttest_ind(a_1, b_1, equal_var = False) 
val

if (val.pvalue>0.05):
  print("Reject Null Hypothesis")
else:
  print("Accept Null Hypothesis")

"""#one sample"""

import scipy.stats as stats
import pandas as pd

t_statistic, p_value = stats.ttest_1samp (a=sep_length, popmean=6) 
print("T test statistic", t_statistic) 
print("Two-sided p-value", p_value)

if (p_value>0.05):
   print("Reject Null Hypothesis")
else:
   print("Accept Null Hypothesis")

"""#Z-test

#one sample
" " "

from statsmodels.stats.weightstats import
ztest as ztest
data = sep_length 
ztest(data, value=30)

"""#Two sample"""

from statsmodels.stats.weightstats import ztest as ztest

data1 sep_length

data2 sep_width

ztest(data1, data2, value=50)